### ISSUE TITLE
Is it still under active development

### ISSUE THREAD

**Issue by xiconet** [WrtApp/wreditor#1]
Hello,
I very much like your idea, especially when I see the "Wreditor will implement:..' features list. This is not an issue, rather a feature request, i.e:
- What are the actual current features?
- Do you plan to continue your project's development?

**Comment by billpatrianakos** [comment]
Right now we're not developing Wreditor very actively. It's the kind of project that kind of hits a ceiling of how many features you can add to it before you can call it complete. I would say that Wreditor is a starting point for integrating a Markdown/code editor into existing projects.

Right now Wreditor lets you write. You can start up a simple server, navigate to localhost and use it. You can also download whatever you write in Wreditor to a text file. It also supports a bunch of themes and full screen editing and markdown live previews.

It's a real simple HTML/CSS/JS project so the best way to get an idea of what it does is to download it, put the folder in a directory where you have a server that'll serve it (or just use the built in server), and check it out.

**Comment by xiconet** [comment]
Thanks for this clarification.
